import { StockInput } from "../types/stockTypes";

export const MOCK_STOCKS: StockInput[] = [
  {
    symbol: "HDFCBANK.NSE",
    name: "HDFC Bank",
    sector: "Financial Sector",
    qty: 50,
    buyPrice: 1490,
  },
  {
    symbol: "BAJFINANCE.NS",
    name: "Bajaj Finance",
    sector: "Financial Sector",
    qty: 15,
    buyPrice: 6466,
  },
  {
    symbol: "532174.BO",
    name: "ICICI Bank",
    sector: "Financial Sector",
    qty: 84,
    buyPrice: 780,
  },
  {
    symbol: "544252.BO",
    name: "Bajaj Housing",
    sector: "Financial Sector",
    qty: 504,
    buyPrice: 130,
  },
  {
    symbol: "511577.BO",
    name: "Savani Financials",
    sector: "Financial Sector",
    qty: 1080,
    buyPrice: 24,
  },
  {
    symbol: "AFFLE.NS",
    name: "Affle India",
    sector: "Tech Sector",
    qty: 50,
    buyPrice: 1151,
  },
  {
    symbol: "LTIM.NS",
    name: "LTI Mindtree",
    sector: "Tech Sector",
    qty: 16,
    buyPrice: 4775,
  },
  {
    symbol: "542651.BO",
    name: "KPIT Tech",
    sector: "Tech Sector",
    qty: 61,
    buyPrice: 672,
  },
  {
    symbol: "544028.BO",
    name: "Tata Tech",
    sector: "Tech Sector",
    qty: 63,
    buyPrice: 1072,
  },
  {
    symbol: "544107.BO",
    name: "BLS E-Services",
    sector: "Tech Sector",
    qty: 191,
    buyPrice: 232,
  },
  {
    symbol: "532790.BO",
    name: "Tanla Platforms",
    sector: "Tech Sector",
    qty: 45,
    buyPrice: 1134,
  },
  {
    symbol: "DMART.NS",
    name: "Avenue Supermarts",
    sector: "Consumer Sector",
    qty: 27,
    buyPrice: 3777,
  },
  {
    symbol: "532540.BO",
    name: "Tata Consumer",
    sector: "Consumer Sector",
    qty: 90,
    buyPrice: 845,
  },
  {
    symbol: "500331.BO",
    name: "Pidilite Industries",
    sector: "Consumer Sector",
    qty: 36,
    buyPrice: 2376,
  },
  {
    symbol: "500400.BO",
    name: "Tata Power",
    sector: "Power Sector",
    qty: 225,
    buyPrice: 224,
  },
  {
    symbol: "542323.BO",
    name: "KPI Green Energy",
    sector: "Power Sector",
    qty: 50,
    buyPrice: 875,
  },
  {
    symbol: "532667.BO",
    name: "Suzlon Energy",
    sector: "Power Sector",
    qty: 450,
    buyPrice: 44,
  },
  {
    symbol: "542851.BO",
    name: "Gensol Engineering",
    sector: "Power Sector",
    qty: 45,
    buyPrice: 998,
  },
  {
    symbol: "543517.BO",
    name: "Hariom Pipes",
    sector: "Pipe Sector",
    qty: 60,
    buyPrice: 580,
  },
  {
    symbol: "ASTRAL.NS",
    name: "Astral Ltd",
    sector: "Pipe Sector",
    qty: 56,
    buyPrice: 1517,
  },
  {
    symbol: "542652.BO",
    name: "Polycab India",
    sector: "Pipe Sector",
    qty: 28,
    buyPrice: 2818,
  },
  {
    symbol: "543318.BO",
    name: "Clean Science",
    sector: "Others",
    qty: 32,
    buyPrice: 1610,
  },
  {
    symbol: "506401.BO",
    name: "Deepak Nitrite",
    sector: "Others",
    qty: 27,
    buyPrice: 2248,
  },
  {
    symbol: "541557.BO",
    name: "Fine Organic",
    sector: "Others",
    qty: 16,
    buyPrice: 4284,
  },
  {
    symbol: "533282.BO",
    name: "Gravita India",
    sector: "Others",
    qty: 8,
    buyPrice: 2037,
  },
  {
    symbol: "540719.BO",
    name: "SBI Life",
    sector: "Others",
    qty: 49,
    buyPrice: 1197,
  },
];
